### ISSUE TITLE
Error during Notepad++ installation

### ISSUE THREAD

**Issue by madoar** [PlayOnLinux/POL-POM-5#695]
I've just tried to install Notepad++ on my laptop.
The important point here is, that I haven't run POL 5 on this PC before. I've started POL 5 in IntelliJ.
After running the installation of Notepad++ I got the following error:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'repository' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:698)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
	at org.phoenicis.scripts.nashorn.NashornEngineFactory.lambda$createEngine$0(NashornEngineFactory.java:66)
	at jdk.nashorn.internal.scripts.Script$Recompilation$105$74$\^eval\_.WineShortcut([Functions, Shortcuts, Wine]:5)
	at jdk.nashorn.internal.scripts.Script$Recompilation$41$564$\^eval\_.go([Functions, QuickScript, InstallerScript]:92)
	at jdk.nashorn.internal.scripts.Script$19$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:45)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

In addition I think that the Mono installation didn't work as intended. Because I got two different windows asking me to install Mono. I think one was in the JavaFX POL 5 design, while the second one looked like a window designed for wine.

**Comment by qparis** [comment]
I think this problem comes from the fact that you replaced the Repository bean by a RepositoryManager bean

**Comment by madoar** [comment]
I think you're right. I'll look into this later today.

**Comment by madoar** [comment]
I think we should add an application installation test, to ensure that changes to the Java code base don't break our scripts. The problem here is, that we would need a way to silently install an application without the need for user inputs (e.g. clicks on buttons), I don't know if this is possible to do currently.

@qparis can you take a look at issue #674? It would be quite nice if my PRs are automatically tested :)

**Comment by Linkaan** [comment]
I get the same error message trying to install steam with the latest version available on git although it works fine with https://github.com/PlayOnLinux/POL-POM-5/commit/5b552dcb464adc8f933b9d80c6e203fe3c4bc5e6

**Comment by Durendal** [comment]
I am also receiving this issue when trying to install League of Legends on Linux Mint 18.1 x86_64

**Comment by madoar** [comment]
This should be fixed with the merges by @qparis 10 minutes ago.
Can you pls try again with the newest commits?

**Comment by Durendal** [comment]
The latest merges seem to have fixed things on my end, thanks for your prompt reply!

**Comment by Linkaan** [comment]
Now I no longer receive this error, however there is still an issue trying to start Age of Empires II HD but since that is a game-specific issue I should probably post that somewhere else?

**Comment by madoar** [comment]
Yes, pls open a new Issue with your received error.
I'll close this issue now, because the first described error has been solved.

**Comment by plata** [comment]
@Linkaan you should open game specific issues in PlayOnLinux/Scripts. I'm curious what issue you have in AoE II as I play it sometimes myself and it works like a charm. In case it should be the broken launcher: That's a wine issue. Just click the top left button.
